### ISSUE TITLE
Does this work in spite of the promise unfullfilment issue on Android 7+ ?

### ISSUE THREAD

**Issue by AliaMYH** [antoniopresto/react-native-local-mongodb#29]
I've been searching for a good alternative for persistent storage to AsyncStorage, because of the following known issue: 

#https://github.com/facebook/react-native/issues/14101#issuecomment-345563563

This package seems to use AsyncStorage in its functionality, if I understood the documentation correctly. Given the above issue, where promises are not resolved or rejected in AsyncStorage.. does the package still work as expected ?

**Comment by antoniopresto** [comment]
It does not seem to matter, but this lib uses AsyncStorage with callback. I have no problems with this issue anyway

**Comment by joaopiopedreira** [comment]
Looking at the source code, we could use a package with a persistent storage other than AsyncStorage.

For example, we could pick one of the persistors used in redux-persist (the following one uses the file system to persist). Because they expose an api similar to AsyncStorage (getItem, setItem, etc.), there should be no problem.

Something like the following should work:
```
import FSStorage, { CacheDir } from 'redux-persist-fs-storage';
const db = new DataStore({filename: 'db.visits',storage: FSStorage(CacheDir, 'myApp')});
await db.loadDatabaseAsync();
(...)
``` 
The above example would create a folder called "myApp" in cache storage for iOS and Android.

I cannot test this because my app is currently on RN expo. Once I detach, I'll be able to test it.

@antoniopresto , do you think this is feasible?

**Comment by antoniopresto** [comment]
I need to test, but I think so. We simply need the *Item methods

**Comment by maelfosso** [comment]
Did you test it ?
